// <auto-generated />
using System;
using Coflnet.Sky.SkyAuctionTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SkyAuctionTracker.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20211105222107_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Coflnet.Sky.SkyAuctionTracker.Models.Flip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("AuctionUUID")
                        .HasColumnType("bigint");

                    b.Property<int>("FinderType")
                        .HasColumnType("int");

                    b.Property<int>("TargetPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionUUID");

                    b.ToTable("Flips");
                });

            modelBuilder.Entity("Coflnet.Sky.SkyAuctionTracker.Models.FlipEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("AuctionUUID")
                        .HasColumnType("bigint");

                    b.Property<int>("FlipEventType")
                        .HasColumnType("int");

                    b.Property<long>("PlayerUUID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerUUID");

                    b.HasIndex("AuctionUUID", "FlipEventType");

                    b.ToTable("FlipEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
